### ISSUE TITLE
Offline functionality

### ISSUE THREAD

**Issue by JakobTopholt** [aau-giraf/api_client#102]
All of these should be well explained

Prioritized list of features that should be available offline:

Citizen features: Limited to current week.
1.1 View weekplan.
1.2 View activity.
1.3 Mark activity as completed.
1.4 Timer functionality.
Guardian features: Limited to current week.
2.1 View weekplan.
2.2 View activity.
2.3 Cancel activity.
2.4 Timer functionality.
2.5 Edit weekplan.
Guardian features:
3.1 Take picture as pictogram.
3.2 Create/delete weekplans.
3.3 All functions from point 2 just not limited to the current week.

## Subtasks
- [ ] As a developer I need code infrastructure for a local database and model adapters in order to implement offline functionality [#72](https://github.com/aau-giraf/api_client/issues/72)
- [ ] As a guardian I would like to be able to log in when offline if I have been logged in online before [#388](https://github.com/aau-giraf/weekplanner/issues/388)
- [ ] As a guardian I would like to be able to take a picture to use as a pictogram in offline mode and optionally sync it when online again. [#397](https://github.com/aau-giraf/weekplanner/issues/397)
- [ ] As a citizen I would like to mark an activity in the current week as completed while offline.[ #400](https://github.com/aau-giraf/weekplanner/issues/400)
- [ ] As a citizen I would like to use an activity’s timer while offline. [#402](https://github.com/aau-giraf/weekplanner/issues/402)
- [ ] As a guardian I would like to edit the weekplan for the current week while offline. [#409](https://github.com/aau-giraf/weekplanner/issues/409)
- [ ] As a guardian I would like to create and delete weekplans while offline [#410](https://github.com/aau-giraf/weekplanner/issues/410)
- [ ] As a guardian I would like to cancel activities in the current weekplan while offline. [#405](https://github.com/aau-giraf/weekplanner/issues/405)
- [ ] As a guardian I would like to use the timer functionality in the current weekplan while offline. [#406](https://github.com/aau-giraf/weekplanner/issues/406)
- [ ] As a guardian I would like to edit the weekplan's activities for the current week while offline. [#407](https://github.com/aau-giraf/weekplanner/issues/407)
- [ ] As a guardian I would like to choose the current week in the weekplan selector screen while offline [#408](https://github.com/aau-giraf/weekplanner/issues/408)
- ~~As a guardian I would like to access and edit a citizen’s settings while offline [#412](https://github.com/aau-giraf/weekplanner/issues/412)~~
- [ ] As a citizen I would like to be able to view my activities and my weekplan for the current week while offline. [#414](https://github.com/aau-giraf/weekplanner/issues/414)
- [ ] As a Guardian I would like to view the current weekplan and activities of my chosen citizen while offline. [#415](https://github.com/aau-giraf/weekplanner/issues/415)
- [ ] As a guardian I would like to have the pictograms that are used in my citizens' week plans to be available offline [#632](https://github.com/aau-giraf/weekplanner/issues/632)
